name: Deploy Infrastructure

on:
  pull_request:
    branches:
      - uat
      - prod
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy
        required: true
        type: choice
        options: [dev, uat, prod]
        default: dev
      action:
        description: Terraform action
        required: true
        type: choice
        options: [plan, apply]
        default: apply
      workload:
        description: What changed / what to deploy
        required: false
        type: choice
        options: [all, infra, frontend, backend, app]
        default: all
      frontend_image_tag:
        description: Frontend Docker image tag
        required: false
        default: latest
      backend_image_tag:
        description: Backend Docker image tag
        required: false
        default: latest
      allow_replacement:
        description: Allow destructive/replacement changes
        required: false
        type: boolean
        default: false

  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      action:
        required: true
        type: string
      workload:
        required: false
        type: string
        default: all
      frontend_image_tag:
        required: false
        type: string
        default: latest
      backend_image_tag:
        required: false
        type: string
        default: latest
      allow_replacement:
        required: false
        type: boolean
        default: false
    secrets:
      DB_PASSWORD:
        required: true

permissions:
  id-token: write
  contents: read
  pull-requests: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  BOOTSTRAP_ROLE_ARN: ${{ vars.BOOTSTRAP_ROLE_ARN }}
  TF_STATE_BUCKET: ${{ vars.TF_STATE_BUCKET }}
  TERRAFORM_VERSION: ${{ vars.TERRAFORM_VERSION }}
  APP_DIR: .

jobs:

  validate-promotion-path:
    name: Validate PR Promotion Path
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
